spring:
  application:
    name: Nexiles OPC UA Client Example

logging:
  level:
    com.nexiles: DEBUG
    org.eclipse.milo: INFO
    org.apache.camel: DEBUG

nexiles:
  # endpoint: milo-client:tcp://192.168.123.2:4840?allowedSecurityPolicies=None&node=RAW(ns=3;s="103_Servo_G"."M150_Data"."POS_ACT")
  # endpoint: milo-client:tcp://127.0.0.1:12686/example?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=2;s=HelloWorld/ScalarTypes/Double)
  endpoint: milo-client:tcp://10.114.220.141:21381/?allowedSecurityPolicies=None&samplingInterval=500

camel:
  component:
    milo-client:
      default-configuration:
        allowed-security-policies: None
        override-host: true
